#! /bin/sh
# char-test --- %c specifier 
# Copyright (C) 2001 Gary V. Vaughan
# Originally by Gary V. Vaughan <gary@gnu.org>, 2001
# This file is part of Snprintfv.
#
# Snprintfv is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Snprintfv is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
# As a special exception to the GNU General Public License, if you
# distribute this file as part of a program that also links with and
# uses the libopts library from AutoGen, you may include it under
# the same distribution terms used by the libopts library.

# Code:

# Common definitions
if test -z "$srcdir"; then
    srcdir=`echo "$0" | sed 's,[^/]*$,,'`
    test "$srcdir" = "$0" && srcdir=.
    test -z "$srcdir" && srcdir=.
    test "${VERBOSE+set}" != set && VERBOSE=1
fi
. $srcdir/defs


# this is the output we should expect to see
cat <<\EOF >ok
1 a
*** printfv returned 3 chars.
2 startBend
*** printfv returned 11 chars.
3     c
*** printfv returned 7 chars.
4          D
*** printfv returned 12 chars.
5 *** printfv returned ERROR (invalid flags).
6 *** printfv returned ERROR (invalid flags).
7 *** printfv returned ERROR (invalid flags).
8 *** printfv returned ERROR (invalid flags).
9 *** printfv returned ERROR (invalid flags).
10 *** printfv returned ERROR (invalid flags).
11 X    
*** printfv returned 8 chars.
12 Y         
*** printfv returned 13 chars.
13 start*** printfv returned ERROR (invalid flags).
14 start*** printfv returned ERROR (invalid flags).
EOF

cat <<\EOF >errok
EOF

# straightforward string output
$SNPRINTFV '1 %c' a 2> err | tee -ai out >&2
$SNPRINTFV '2 start%cend' B 2> err | tee -ai out >&2

# test width flag
$SNPRINTFV '3 %5c' c 2> err | tee -ai out >&2
$SNPRINTFV '4 %10c' D 2> err | tee -ai out >&2

# test precision flag
$SNPRINTFV '5 %.5c' @ 2> err | tee -ai out >&2
$SNPRINTFV '6 %.10c' '#' 2> err | tee -ai out >&2

# test zero padding
$SNPRINTFV '7 %05c' 1 2> err | tee -ai out >&2
$SNPRINTFV '8 %010c' 2 2> err | tee -ai out >&2
$SNPRINTFV '9 %0.5c' 3 2> err | tee -ai out >&2
$SNPRINTFV '10 %0.10c' 4 2> err | tee -ai out >&2

# test left justfy flag
$SNPRINTFV '11 %-5c' X 2> err | tee -ai out >&2
$SNPRINTFV '12 %-10c' Y 2> err | tee -ai out >&2

# try a bizarre combination
$SNPRINTFV '13 start%09.5cend' z 2> err | tee -ai out >&2
$SNPRINTFV '14 start%-09.5cend' y 2> err | tee -ai out >&2

# Test against expected output
if ${CMP} -s out ok; then
    :
else
    echo "ok:" >&2
    cat ok >&2
    exit 1
fi

# Munge error output to remove leading directories, `lt-' or trailing `.exe'
sed -e "s,^[^:]*[lt-]*snprintfv-test[.ex]*:,snprintfv-test:," err >sederr \
    && mv sederr err

# Show stderr if doesn't match expected output if VERBOSE == 1
if "$CMP" -s err errok; then
    :
else
    echo "err:" >&2
    cat err >&2
    echo "errok:" >&2
    cat errok >&2
    exit 1
fi

# char-test ends here
