#! /bin/sh
#  -*- Mode: Sh -*- 
# extend-test --- %P (for pig latin) specifier
# Copyright (C) 1999 Gary V. Vaughan
# Originally by Gary V. Vaughan <gvv@techie.com>, 1999
# This file is part of Snprintfv.
#
# Snprintfv is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Snprintfv is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
# As a special exception to the GNU General Public License, if you
# distribute this file as part of a program that also links with and
# uses the libopts library from AutoGen, you may include it under
# the same distribution terms used by the libopts library.

# Code:

# Common definitions
if test -z "$srcdir"; then
    srcdir=`echo "$0" | sed 's,[^/]*$,,'`
    test "$srcdir" = "$0" && srcdir=.
    test -z "$srcdir" && srcdir=.
    test "${VERBOSE+set}" != set && VERBOSE=1
fi
. $srcdir/defs


# this is the output we should expect to see
cat <<\EOF >ok
1 gstrinay
*** printfv returned 10 chars.
2 startgstrinayend
*** printfv returned 18 chars.
3 gstrinay
*** printfv returned 10 chars.
4   gstrinay
*** printfv returned 12 chars.
5 gstri
*** printfv returned 7 chars.
6 gstrinay
*** printfv returned 10 chars.
7 gstrinay
*** printfv returned 10 chars.
8 00gstrinay
*** printfv returned 12 chars.
9 gstri
*** printfv returned 7 chars.
10 gstrinay
*** printfv returned 11 chars.
11 gstrinay
*** printfv returned 11 chars.
12 gstrinay  
*** printfv returned 13 chars.
13 start0000gstriend
*** printfv returned 20 chars.
14 startgstri    end
*** printfv returned 20 chars.
EOF

cat <<\EOF >errok
EOF

# straightforward string output
LTDL_LIBRARY_PATH=$builddir $SNPRINTFV '1 %P' \"string\" 2> err | tee -ai out >&2
LTDL_LIBRARY_PATH=$builddir $SNPRINTFV '2 start%Pend' \"string\" 2> err | tee -ai out >&2

# test width flag
LTDL_LIBRARY_PATH=$builddir $SNPRINTFV '3 %5P' \"string\" 2> err | tee -ai out >&2
LTDL_LIBRARY_PATH=$builddir $SNPRINTFV '4 %10P' \"string\" 2> err | tee -ai out >&2

# test precision flag
LTDL_LIBRARY_PATH=$builddir $SNPRINTFV '5 %.5P' \"string\" 2> err | tee -ai out >&2
LTDL_LIBRARY_PATH=$builddir $SNPRINTFV '6 %.10P' \"string\" 2> err | tee -ai out >&2

# test zero padding
LTDL_LIBRARY_PATH=$builddir $SNPRINTFV '7 %05P' \"string\" 2> err | tee -ai out >&2
LTDL_LIBRARY_PATH=$builddir $SNPRINTFV '8 %010P' \"string\" 2> err | tee -ai out >&2
LTDL_LIBRARY_PATH=$builddir $SNPRINTFV '9 %0.5P' \"string\" 2> err | tee -ai out >&2
LTDL_LIBRARY_PATH=$builddir $SNPRINTFV '10 %0.10P' \"string\" 2> err | tee -ai out >&2

# test left justfy flag
LTDL_LIBRARY_PATH=$builddir $SNPRINTFV '11 %-5P' \"string\" 2> err | tee -ai out >&2
LTDL_LIBRARY_PATH=$builddir $SNPRINTFV '12 %-10P' \"string\" 2> err | tee -ai out >&2

# try a bizarre combination
LTDL_LIBRARY_PATH=$builddir $SNPRINTFV '13 start%09.5Pend' \"string\" 2> err | tee -ai out >&2
LTDL_LIBRARY_PATH=$builddir $SNPRINTFV '14 start%-09.5Pend' \"string\" 2> err | tee -ai out >&2

# Test against expected output
if ${CMP} -s out ok; then
    :
else
    echo "ok:" >&2
    cat ok >&2
    exit 1
fi

# Munge error output to remove leading directories, `lt-' or trailing `.exe'
sed -e "s,^[^:]*[lt-]*snprintfv-test[.ex]*:,snprintfv-test:," err >sederr \
    && mv sederr err

# Show stderr if doesn't match expected output if VERBOSE == 1
if "$CMP" -s err errok; then
    :
else
    echo "err:" >&2
    cat err >&2
    echo "errok:" >&2
    cat errok >&2
    exit 1
fi

# string-test ends here
