#! /bin/sh
#  -*- Mode: Sh -*- 
# limit-test --- check buffer size limiting
# Copyright (C) 1999, 2000 Gary V. Vaughan
# Originally by Gary V. Vaughan <gvv@techie.com>, 1999
# This file is part of Snprintfv.
#
# Snprintfv is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Snprintfv is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
# As a special exception to the GNU General Public License, if you
# distribute this file as part of a program that also links with and
# uses the libopts library from AutoGen, you may include it under
# the same distribution terms used by the libopts library.

# Code:

# Common definitions
if test -z "$srcdir"; then
    srcdir=`echo "$0" | sed 's,[^/]*$,,'`
    test "$srcdir" = "$0" && srcdir=.
    test -z "$srcdir" && srcdir=.
    test "${VERBOSE+set}" != set && VERBOSE=1
fi
. $srcdir/defs


# this is the output we should expect to see
cat <<\EOF >ok
1 abc
*** snprintfv returned 5 chars.
2 abcd
*** snprintfv returned 7 chars.
3 abcd
*** snprintfv returned 9 chars.
4 abc
*** snprintfv returned 5 chars.
5 abcd
*** snprintfv returned 7 chars.
6 abcd
*** snprintfv returned 9 chars.
7 a bc
*** snprintfv returned 6 chars.
8 ab cd
*** snprintfv returned 8 chars.
9 abc d
*** snprintfv returned 10 chars.
EOF

cat <<\EOF > errok
EOF

# basic tests
$SNPRINTFV -f snprintfv -n 7 '1 abc' 2>>err | tee -ai out >&2
$SNPRINTFV -f snprintfv -n 7 '2 abcde' 2>>err | tee -ai out >&2
$SNPRINTFV -f snprintfv -n 7 '3 abcdefg' 2>>err | tee -ai out >&2

# test with specifiers
$SNPRINTFV -f snprintfv -n 7 '4 %s' abc 2>>err | tee -ai out >&2
$SNPRINTFV -f snprintfv -n 7 '5 %s' abcde 2>>err | tee -ai out >&2
$SNPRINTFV -f snprintfv -n 7 '6 %s' abcdefg 2>>err | tee -ai out >&2
$SNPRINTFV -f snprintfv -n 8 '7 %s %s' a bc 2>>err | tee -ai out >&2
$SNPRINTFV -f snprintfv -n 8 '8 %s %s' ab cde 2>>err | tee -ai out >&2
$SNPRINTFV -f snprintfv -n 8 '9 %s %s' abc defg 2>>err | tee -ai out >&2

# Test against expected output
if ${CMP} -s out ok; then
    :
else
    echo "ok:" >&2
    cat ok >&2
    exit 1
fi

# Munge error output to remove leading directories, `lt-' or trailing `.exe'
sed -e "s,^[^:]*[lt-]*snprintfv-test[.ex]*:,snprintfv-test:," err >sederr \
    && mv sederr err

# Show stderr if doesn't match expected output if VERBOSE == 1
if "$CMP" -s err errok; then
    :
else
    echo "err:" >&2
    cat err >&2
    echo "errok:" >&2
    cat errok >&2
    exit 1
fi

# limit-test ends here
