#! /bin/sh
# octal-test --- %o specifier
# Copyright (C) 2001 Gary V. Vaughan
# Originally by Gary V. Vaughan <gary@gnu.org>, 2001
# This file is part of Snprintfv.
#
# Snprintfv is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Snprintfv is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
# As a special exception to the GNU General Public License, if you
# distribute this file as part of a program that also links with and
# uses the libopts library from AutoGen, you may include it under
# the same distribution terms used by the libopts library.

# Common definitions
if test -z "$srcdir"; then
    srcdir=`echo "$0" | sed 's,[^/]*$,,'`
    test "$srcdir" = "$0" && srcdir=.
    test -z "$srcdir" && srcdir=.
    test "${VERBOSE+set}" != set && VERBOSE=1
fi
. $srcdir/defs


# this is the output we should expect to see
cat <<\EOF >ok
1 12
*** printfv returned 4 chars.
2 >24<
*** printfv returned 6 chars.
3 515
*** printfv returned 5 chars.
4         50
*** printfv returned 12 chars.
5 154403
*** printfv returned 8 chars.
6 202152
*** printfv returned 8 chars.
7 000227721
*** printfv returned 11 chars.
8 21270
*** printfv returned 7 chars.
9 23417
*** printfv returned 7 chars.
10 1762
*** printfv returned 7 chars.
11 2127
*** printfv returned 7 chars.
12 02274
*** printfv returned 8 chars.
13 02441
*** printfv returned 8 chars.
14 2606.
*** printfv returned 8 chars.
15 2753.
*** printfv returned 8 chars.
16 3120 .
*** printfv returned 9 chars.
17 3265
*** printfv returned 7 chars.
18 3432
*** printfv returned 7 chars.
19  3433
*** printfv returned 8 chars.
20 3435
*** printfv returned 7 chars.
21 3436
*** printfv returned 7 chars.
22 03577
*** printfv returned 8 chars.
23 00003554
*** printfv returned 11 chars.
24      2322
*** printfv returned 12 chars.
25     02322
*** printfv returned 12 chars.
26 000002322
*** printfv returned 12 chars.
27    002322
*** printfv returned 12 chars.
28   0002322
*** printfv returned 12 chars.
29 000002322
*** printfv returned 12 chars.
30 002322   
*** printfv returned 12 chars.
31 0002322  
*** printfv returned 12 chars.
32 002322   
*** printfv returned 12 chars.
EOF

cat <<\EOF >errok
EOF

# straight forward integer output
$SNPRINTFV '1 %o' 10 2>> err | tee -ai out >&2
$SNPRINTFV '2 >%o<' 20 2>> err | tee -ai out >&2

# test width flag
$SNPRINTFV '3 %2o' 333 2>> err | tee -ai out >&2
$SNPRINTFV '4 %10o' 40 2>> err | tee -ai out >&2

# test precision flag
$SNPRINTFV '5 %.3o' 55555 2>> err | tee -ai out >&2
$SNPRINTFV '6 %.6o' 66666 2>> err | tee -ai out >&2
$SNPRINTFV '7 %.9o' 77777 2>> err | tee -ai out >&2

# test zero padding
$SNPRINTFV '8 %03o' 8888 2>> err | tee -ai out >&2
$SNPRINTFV '9 %0.3o' 9999 2>> err | tee -ai out >&2

$SNPRINTFV '10 %04o' 1010 2>> err | tee -ai out >&2
$SNPRINTFV '11 %0.4o' 1111 2>> err | tee -ai out >&2

$SNPRINTFV '12 %05o' 1212 2>> err | tee -ai out >&2
$SNPRINTFV '13 %0.5o' 1313 2>> err | tee -ai out >&2

# test grouping flag
# TODO!

# test left justfy flag
$SNPRINTFV '14 %-3o.' 1414 2>> err | tee -ai out >&2
$SNPRINTFV '15 %-4o.' 1515 2>> err | tee -ai out >&2
$SNPRINTFV '16 %-5o.' 1616 2>> err | tee -ai out >&2

# test sign flag
$SNPRINTFV '17 %+o' 1717 2>> err | tee -ai out >&2

# test blank flag
$SNPRINTFV '18 % o' 1818 2>> err | tee -ai out >&2
$SNPRINTFV '19 % 5o' 1819 2>> err | tee -ai out >&2
$SNPRINTFV '20 %+ o' 1821 2>> err | tee -ai out >&2
$SNPRINTFV '21 % +o' 1822 2>> err | tee -ai out >&2

# test alternate form flag
$SNPRINTFV '22 %#o' 1919 2>> err | tee -ai out >&2
$SNPRINTFV '23 %#08o' 1900 2>>err | tee -ai out >&2

# combining width and precision
$SNPRINTFV '24 %9.3o' 1234 2>> err | tee -ai out >&2
$SNPRINTFV '25 %#9.3o' 1234 2>> err | tee -ai out >&2
$SNPRINTFV '26 %09.3o' 1234 2>> err | tee -ai out >&2
$SNPRINTFV '27 %9.6o' 1234 2>> err | tee -ai out >&2
$SNPRINTFV '28 %#9.6o' 1234 2>> err | tee -ai out >&2
$SNPRINTFV '29 %09.6o' 1234 2>> err | tee -ai out >&2
$SNPRINTFV '30 %-9.6o' 1234 2>> err | tee -ai out >&2
$SNPRINTFV '31 %-#9.6o' 1234 2>> err | tee -ai out >&2
$SNPRINTFV '32 %-09.6o' 1234 2>> err | tee -ai out >&2

# Test against expected output
if ${CMP} -s out ok; then
    :
else
    echo "ok:" >&2
    cat ok >&2
    exit 1
fi

# Munge error output to remove leading directories, `lt-' or trailing `.exe'
sed -e "s,^[^:]*[lt-]*snprintfv-test[.ex]*:,snprintfv-test:," err >sederr \
    && mv sederr err

# Show stderr if doesn't match expected output if VERBOSE == 1
if "$CMP" -s err errok; then
    :
else
    echo "err:" >&2
    cat err >&2
    echo "errok:" >&2
    cat errok >&2
    exit 1
fi

# octal-test ends here
