#! /bin/sh
#  -*- Mode: Sh -*- 
# string-test --- %s specifier
# Copyright (C) 1998, 1999 Gary V. Vaughan
# Originally by Gary V. Vaughan <gvv@techie.com>, 1998
# This file is part of Snprintfv.
#
# Snprintfv is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Snprintfv is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
# As a special exception to the GNU General Public License, if you
# distribute this file as part of a program that also links with and
# uses the libopts library from AutoGen, you may include it under
# the same distribution terms used by the libopts library.

# Code:

# Common definitions
if test -z "$srcdir"; then
    srcdir=`echo "$0" | sed 's,[^/]*$,,'`
    test "$srcdir" = "$0" && srcdir=.
    test -z "$srcdir" && srcdir=.
    test "${VERBOSE+set}" != set && VERBOSE=1
fi
. $srcdir/defs


# this is the output we should expect to see
cat <<\EOF >ok
1 string
*** printfv returned 8 chars.
2 startstringend
*** printfv returned 16 chars.
3 string
*** printfv returned 8 chars.
4     string
*** printfv returned 12 chars.
5 strin
*** printfv returned 7 chars.
6 string
*** printfv returned 8 chars.
7 string
*** printfv returned 8 chars.
8 0000string
*** printfv returned 12 chars.
9 strin
*** printfv returned 7 chars.
10 string
*** printfv returned 9 chars.
11 string
*** printfv returned 9 chars.
12 string    
*** printfv returned 13 chars.
13 start0000strinend
*** printfv returned 20 chars.
14 startstrin    end
*** printfv returned 20 chars.
EOF

cat <<\EOF >errok
EOF

# straightforward string output
$SNPRINTFV '1 %s' \"string\" 2> err | tee -ai out >&2
$SNPRINTFV '2 start%send' \"string\" 2> err | tee -ai out >&2

# test width flag
$SNPRINTFV '3 %5s' \"string\" 2> err | tee -ai out >&2
$SNPRINTFV '4 %10s' \"string\" 2> err | tee -ai out >&2

# test precision flag
$SNPRINTFV '5 %.5s' \"string\" 2> err | tee -ai out >&2
$SNPRINTFV '6 %.10s' \"string\" 2> err | tee -ai out >&2

# test zero padding
$SNPRINTFV '7 %05s' \"string\" 2> err | tee -ai out >&2
$SNPRINTFV '8 %010s' \"string\" 2> err | tee -ai out >&2
$SNPRINTFV '9 %0.5s' \"string\" 2> err | tee -ai out >&2
$SNPRINTFV '10 %0.10s' \"string\" 2> err | tee -ai out >&2

# test left justfy flag
$SNPRINTFV '11 %-5s' \"string\" 2> err | tee -ai out >&2
$SNPRINTFV '12 %-10s' \"string\" 2> err | tee -ai out >&2

# try a bizarre combination
$SNPRINTFV '13 start%09.5send' \"string\" 2> err | tee -ai out >&2
$SNPRINTFV '14 start%-09.5send' \"string\" 2> err | tee -ai out >&2

# Test against expected output
if ${CMP} -s out ok; then
    :
else
    echo "ok:" >&2
    cat ok >&2
    exit 1
fi

# Munge error output to remove leading directories, `lt-' or trailing `.exe'
sed -e "s,^[^:]*[lt-]*snprintfv-test[.ex]*:,snprintfv-test:," err >sederr \
    && mv sederr err

# Show stderr if doesn't match expected output if VERBOSE == 1
if "$CMP" -s err errok; then
    :
else
    echo "err:" >&2
    cat err >&2
    echo "errok:" >&2
    cat errok >&2
    exit 1
fi

# string-test ends here
