#!/bin/sh

: ${srcdir=.}
builddir=`pwd`
base=`basename $1`
top_builddir=`pwd`/..

cd $srcdir
case $1 in
  *.st)
    base=`echo $base | sed 's/\.st$//' `
    build_base=${builddir}/$base

    $top_builddir/gst -rI $top_builddir/gst.im ${base}.st > $build_base.log 2>&1
    ERROR_CODE=$?

    if test $ERROR_CODE = 0; then
      diff -c ${base}.ok $build_base.log > $build_base.diff && rm $build_base.diff
    else
      exit $ERROR_CODE
    fi
    ;;

  *Test)
    grep ^$base $builddir/ANSI.log > /dev/null 2>&1 && rm $builddir/ANSI.log
    $top_builddir/gst -QI $builddir/gst.im AnsiRun.st -a $base >> $builddir/ANSI.log 2>&1
    exit $?
    ;;
esac
