\input texinfo.tex  @c -*- texinfo -*-
@c %**start of header (This is for running Texinfo on a region.)
@setfilename gst-libs.info
@settitle GNU Smalltalk Library Reference
@setchapternewpage odd
@c %**end of header (This is for running Texinfo on a region.)

@c ******************************************* Values and macros *********

@include vers-libs.texi
@ifclear UPDATE-MONTH
@set UPDATE-MONTH @value{UPDATED}
@end ifclear

@macro bulletize{a}
@item
\a\
@end macro

@c ********************************************** Texinfo 4.0 macros *****

@c Emulate the `@ifnottex' command which is found in Texinfo 4.0
@iftex
@set IS_TEX
@end iftex

@c ***********************************************************************

@macro gst{}
@sc{gnu} Smalltalk
@end macro
@macro gnu{}
@sc{gnu}
@end macro

@dircategory GNU Smalltalk
@direntry
     * Libraries: (gst-libs).                The GNU Smalltalk class libraries.
@end direntry

@copying
This file documents GNU Smalltalk Version @value{VERSION}.
It was last updated on @value{UPDATED}.

Copyright @copyright{} 1988-92, 1994-95, 1999-2001 Free Software Foundation, Inc.

This document is released under the terms of the GNU Free Documentation
License as published by the Free Software Foundation; either version 1.1, or
(at your option) any later version.

You should have received a copy of the GNU Free Documentation License along
with GNU Smalltalk; see the file @file{COPYING.DOC}.  If not, write to the Free
Software Foundation, 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.  

There are no Cover Texts and no Invariant Sections; this text, along
with its equivalent in the printed manual, constitutes the Title Page.
@end copying

@setchapternewpage odd

@titlepage
@title @sc{gnu} Smalltalk Library Reference
@subtitle Version @value{VERSION}
@subtitle @value{UPDATE-MONTH}

@author by Paolo Bonzini

@comment  The following two commands start the copyright page.
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@node Top, , , (DIR)
@top

@ifnottex
This document describes the class libraries that are distributed
together with the @gst{} programming language.

@insertcopying
@end ifnottex

@menu
* BLOX::                The GUI library
* TCP::                 The sockets library
* I18N::                The internationalization library
* XML::                 Using the XML library

* Class index::         Index to the classes in the class reference
* Method index::        Index to the method selectors in the class reference
* Cross-reference::     Cross-reference between selectors
@end menu

@node BLOX
@chapter BLOX
@include blox.texi

@node TCP
@chapter TCP
@include tcp.texi

@node I18N
@chapter I18N
@include i18n.texi

@node XML
@chapter XML
@include using-xml.texi

@node Class index
@unnumbered Class index
@printindex cl

@node Method index
@unnumbered Method index
@printindex me

@node Cross-reference
@unnumbered Selector cross-reference
@printindex sl

@iftex
@contents
@end iftex

@bye

Local Variables:
compile-command: "makeinfo -fc 72 gst-libs.texi"
fill-column: 72
End:
