\input texinfo.tex  @c -*- texinfo -*-
@c %**start of header (This is for running Texinfo on a region.)
@setfilename gst-libs.info
@settitle GNU Smalltalk Library Reference
@setchapternewpage odd
@c %**end of header (This is for running Texinfo on a region.)

@c ******************************************* Values and macros *********

@include vers-libs.texi
@ifclear UPDATE-MONTH
@set UPDATE-MONTH @value{UPDATED}
@end ifclear

@macro bulletize{a}
@item
\a\
@end macro

@c ********************************************** Texinfo 4.0 macros *****

@c Emulate the `@ifnottex' command which is found in Texinfo 4.0
@iftex
@set IS_TEX
@end iftex

@c ***********************************************************************

@macro gst{}
@sc{gnu} Smalltalk
@end macro
@macro gnu{}
@sc{gnu}
@end macro

@dircategory Software development
@direntry
* Smalltalk libraries: (gst-libs).      The GNU Smalltalk class libraries.
@end direntry

@copying
@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.2 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with no Front-Cover Texts, and with no Back-Cover
Texts.  A copy of the license is included in the section entitled
``GNU Free Documentation License''.
@end quotation
@end copying

@setchapternewpage odd

@titlepage
@title @sc{gnu} Smalltalk Library Reference
@subtitle Version @value{VERSION}
@subtitle @value{UPDATE-MONTH}

@author by Paolo Bonzini

@comment  The following two commands start the copyright page.
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@node Top, , , (DIR)
@top

@ifnottex
This document describes the class libraries that are distributed
together with the @gst{} programming language.

@insertcopying
@end ifnottex

@menu
* BLOX package::           The GUI library
* Complex package::        Complex number computations
* DBI package::            The database connectivity library
* DebugTools package::     Controlling the execution of Smalltalk processes
* Sockets package::        The sockets library
* Iconv/I18N packages::    The internationalization library
* XML/XPath/XSL packages:: Using the XML library
* ZLib package::           Bindings to the popular data compression library

* Class index::            Index to the classes in the class reference
* Method index::           Index to the method selectors in the class reference
* Cross-reference::        Cross-reference between selectors
@end menu

@node BLOX package
@chapter Graphical users interfaces with BLOX
@include blox.texi

@node Complex package
@chapter Complex number computations
@include complex.texi

@node DBI package
@chapter Database connectivity with DBI
@include dbi.texi

@node DebugTools package
@chapter Controlling Smalltalk processes with DebugTools
@include debug.texi

@node Iconv/I18N packages
@chapter Multilingual and international support with Iconv and I18N
@include i18n.texi

@node Sockets package
@chapter Network programming with Sockets
@include sockets.texi

@node ZLib package
@chapter Compressing and decompressing data with ZLib
@include zlib.texi

@node XML/XPath/XSL packages
@chapter Libraries for the SAX, DOM, XPath and XSLT standards
@include using-xml.texi

@node Class index
@unnumbered Class index
@printindex cl

@node Method index
@unnumbered Method index
@printindex me

@node Cross-reference
@unnumbered Selector cross-reference
@printindex sl

@iftex
@contents
@end iftex

@bye

Local Variables:
compile-command: "makeinfo -fc 72 gst-libs.texi"
fill-column: 72
End:
