"Test out parsing bad instance variable names"

Object subclass: #Rambo
       instanceVariableNames: 'd99ogABCRblammo 9whammo loser! dogbert++'
       classVariableNames: ''
       poolDictionaries: ''
       category: nil
! 

Object subclass: #Rambo
       instanceVariableNames: 'dog!,blammo whammo? loser! dogbert++'
       classVariableNames: ''
       poolDictionaries: ''
       category: nil
! 

